import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navegacion from '@/components/Navegacion'
import FooterPadel from '@/components/footer'
import Providers from './Providers'
import { ComplexNavbar } from '@/components/NavBar'
import imagefondo from '../../public/6328120.jpg'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PadelCharro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className="bg-image min-h-screen w-full max-w-screen-xl mx-auto px-4">
        <Providers>
      <ComplexNavbar/>
      {children}
      <FooterPadel/>
      </Providers>
      </body>
    </html>
  )
}
