import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navegacion from '@/components/Navegacion'
import FooterPadel from '@/components/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PadelCharro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body> 
      <Navegacion/>
      {children}
      <FooterPadel/>
      </body>
    </html>
  )
}
